### PR TITLE
feat: Make graphs optional

### PR DESCRIPTION
**Pull request by hermanschaaf**
This adds a `style` option that allows users to choose between the `graph` style and the original `text` style. The default is `graph`.

#### text

Screenshot 2022-11-22 at 17 26 49

#### graph

Screenshot 2022-11-22 at 17 28 17

This was tested here https://github.com/cloudquery/plugin-sdk/pull/425

Closes https://github.com/netlify/delta-action/issues/330

### CODE REVIEW

**Comment by danez** [comment]
Thanks for the PR. Looks good so far. Could you please add a test case for this. Should be similar to the one we have right now, but with the different style.

**Comment by hermanschaaf** [comment]
@danez Sure, updated the tests 👍

**Review by danez — APPROVED** [review]

**Comment by eduardoboucas** [comment]
@hermanschaaf This is awesome, thank you! ❤️

**Comment by erezrokah** [comment]
Thanks for the PR @hermanschaaf and the quick review and merge @danez and @eduardoboucas 🚀

**Comment by eduardoboucas** [comment]
@erezrokah ❤️🥲

**Pull request merged**
